compareTo() method for case of equal scores
Reason:
compareTo() method violates it's contract, and it is not transitive

Reprodicing:
		List<Tuple> tuples = new LinkedList<>();
		//creating unsorted list with elements with duplicate scores
		for (int i = 0; i < 1000; i++) {
			tuples.add(new Tuple("elem_" + i, (i % 10) * 1.));
		}
		Collections.sort(tuples);

results in:
 java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:714)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:451)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:376)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:182)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
	at java.util.Arrays.sort(Arrays.java:472)
	at java.util.Collections.sort(Collections.java:155)

I know that Jedis.zrangeByScoreWithScores() returns Set<Tuple> which is already sorted.
My use case when I got this error is getting elements from different ZSETs with different ranges, and merging them into List and then sorting it.