Attemot to fix flaky test
Error:  Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.297 s <<< FAILURE! -- in redis.clients.jedis.failover.FailoverIntegrationTest
Error:  redis.clients.jedis.failover.FailoverIntegrationTest.testManualFailoverInflightCommandsWithErrorsPropagateError -- Time elapsed: 0.035 s <<< ERROR!
redis.clients.jedis.exceptions.JedisValidationException: cluster:localhost:29380 failed to connect. Please check configuration and try again.
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider.validateTargetConnection(MultiClusterPooledConnectionProvider.java:481)
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider.setActiveCluster(MultiClusterPooledConnectionProvider.java:526)
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider.setActiveCluster(MultiClusterPooledConnectionProvider.java:494)
	at redis.clients.jedis.failover.FailoverIntegrationTest.testManualFailoverInflightCommandsWithErrorsPropagateError(FailoverIntegrationTest.java:217)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Cluster is not healthy
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider$Cluster.getConnection(MultiClusterPooledConnectionProvider.java:653)
	at redis.clients.jedis.providers.MultiClusterPooledConnectionProvider.validateTargetConnection(MultiClusterPooledConnectionProvider.java:471)
	... 6 more